return {
  { "HiPhish/rainbow-delimiters.nvim",     submodules = false, },
  { "alexghergh/nvim-tmux-navigation" },
  { "catgoose/nvim-colorizer.lua" },
  { "catppuccin/nvim",                     name = "catppuccin", priority = 1000 },
  { "echasnovski/mini.nvim",               version = false },
  { "kristijanhusak/vim-dadbod-completion" },
  { "kristijanhusak/vim-dadbod-ui" },
  { "norcalli/nvim-colorizer.lua" },
  { "nvim-lua/plenary.nvim" },
  { "rbgrouleff/bclose.vim" },
  { "rust-lang/rust.vim" },
  { "tpope/vim-dadbod" },
  { "tpope/vim-obsession" },
  { "vim-airline/vim-airline" },
  { "vim-airline/vim-airline-themes" },
  { "vuciv/golf" },
  -- { "mfussenegger/nvim-dap" },
  -- { "mfussenegger/nvim-dap-python" },
  -- { "nvim-neotest/nvim-nio" },
  -- { "sheerun/vim-polyglot" },
  -- { "theHamsta/nvim-dap-virtual-text" },
  -- { "wookayin/semshi",                     build = ":UpdateRemotePlugins" },
}
