return {
    { "catppuccin/nvim",                     name = "catppuccin",           priority = 1000 },
    { "norcalli/nvim-colorizer.lua" },
    { "sheerun/vim-polyglot" },
    { "lambdalisue/battery.vim" },
    { "vim-airline/vim-airline" },
    { "vim-airline/vim-airline-themes" },
    { "numirias/semshi",                     build = ":UpdateRemotePlugins" },
    { "rbgrouleff/bclose.vim" },
    { "rust-lang/rust.vim" },
    { "alexghergh/nvim-tmux-navigation" },
    { "tpope/vim-obsession" },
    { "tpope/vim-dadbod" },
    { "kristijanhusak/vim-dadbod-ui" },
    { "kristijanhusak/vim-dadbod-completion" },
    { "nvim/nvim-lspconfig" },
    { "nvim-lua/plenary.nvim" },
    --{ "mfussenegger/nvim-dap" },
    --{ "mfussenegger/nvim-dap-python" },
    --{ "nvim-neotest/nvim-nio" },
    --{ "theHamsta/nvim-dap-virtual-text" },
    { 'vuciv/golf' },
    { "HiPhish/rainbow-delimiters.nvim" },
}
