set nu
set relativenumber
set colorcolumn=80
set cul

"Brew prefixes; missing rtp dirs are ignored, so all three are safe to list.
"Linux distro fzf ships into vimfiles/, already in rtp.
set rtp+=/usr/local/opt/fzf
set rtp+=/opt/homebrew/opt/fzf
set rtp+=/home/linuxbrew/.linuxbrew/opt/fzf
set viminfofile=~/.config/vim/viminfo


set listchars=eol:⏎,tab:\|\-▶,space:·,trail:~,extends:>,precedes:<,nbsp:␣
set list
noremap <F5> :set list! relativenumber! nu!<CR>
inoremap <F5> <C-o>:set list! relativenumber! nu!<CR>
cnoremap <F5> <C-c>:set list! relativenumber! nu!<CR>
